### ISSUE TITLE
Syncing on application launch prevents fixing configuration errors

### ISSUE THREAD

**Issue by Keeblo** [etesync/ios#14]
Syncing when the iOS application launches prevents users from fixing configuration errors that cause the application to crash. See my other GitHub Issue for an example of a configuration error (combined with a potential bug) that causes the application to crash.

The workaround that I found was to put my iPhone into airplane mode so that EteSync wouldn't attempt a sync. Then I could change the erroneous configuration. Ideally I wouldn't need to use this workaround.

Thanks for all of the hard work!

**Comment by tasn** [comment]
That's a great workaround, good thinking! :)

Anyhow, I now fixed it. It was annoying even without the issue you described, and it's now fixed.
