### ISSUE TITLE
All-day events show on the wrong day

### ISSUE THREAD

**Issue by iliana** [etesync/ios#15]
Running EteSync 1.3.1 on iOS 13.3.

If my friend using Android creates an all-day event, it shows on iOS on the wrong day. I assume this is due to [vCal not having a method for including timezones in all-day events](https://twitter.com/ticky/status/1016483657698037761). (The event also shows in EteSync on Android with the wrong day but that's less critical...)

Our phones are both in the same timezone as the server.

Some screenshots:

<details><summary>The event on an Android phone's calendar</summary>

![e4eba4ca_6IvJ73sIRA-PSH6nZpuLPw](https://user-images.githubusercontent.com/52814/73712569-57906480-46bf-11ea-9525-fffa30f09411.jpg)
</details>

<details><summary>The event in EteSync on Android with the wrong day</summary>

![84eb7cfb_oP7vN-F1S9SZ-TYrj4HlVg](https://user-images.githubusercontent.com/52814/73712617-81498b80-46bf-11ea-99aa-44f10e67eff3.jpg)
</details>

<details><summary>The event in EteSync on iOS</summary>

![ima_a7ebcc5](https://user-images.githubusercontent.com/52814/73712715-d38aac80-46bf-11ea-9dac-93f5b98234a6.png)
</details>

<details><summary>The event in iOS calendar with the wrong day</summary>

![ima_afd16e6](https://user-images.githubusercontent.com/52814/73712738-e56c4f80-46bf-11ea-8fdc-09f2006f680d.png)
</details>

**Comment by tasn** [comment]
Could you please copy here the raw ical event (the RAW tab)?
What's the correct expected date, the one in the Android screenshot?

**Comment by iliana** [comment]
Correct expected date is the one in the Android screenshot, I think.

Although I haven't tested if creating an all day event on iOS shows as the wrong day (in the opposite direction) on Android.

**Comment by iliana** [comment]
Here’s the raw event on iOS, I can’t seem to
copy the text unfortunately.

![2BF32797-543C-490A-90ED-DA4EF3C1FCB7](https://user-images.githubusercontent.com/52814/74093148-ca645b80-4a82-11ea-84f3-15178f1f29a7.jpeg)

**Comment by tasn** [comment]
Thanks for the info. I'm looking into it!

**Comment by tasn** [comment]
I tried to verify it locally, and I wasn't able to. It works as expected, both ways. :|

What timezone are you (iOS) on? Have you changed timezones since it synced?

**Comment by iliana** [comment]
US/Pacific (currently UTC-8). The calendar itself and the other parties using the calendar are also UTC-8.

Is there a DST-related issue?

**Comment by tasn** [comment]
I don't think so, but I can try setting my phone to UTC-8 and see if that makes a difference. :)

**Comment by tasn** [comment]
Good news, I managed to reproduce the issue, and I think you are right, it could very well be DST related! I don't think I'll be able to solve it today, but I hope to solve it tomorrow or the day after.

Thanks a lot for your help and the report.

**Comment by tasn** [comment]
Sorry, haven't solved it yet, though I haven't forgotten about it either. :)

**Comment by tasn** [comment]
It should now be fixed. In order to actually see the effects you would need to go to the settings screen -> disable calendar sync -> enable calendar sync -> start a new sync.

Please let me know if it work for you.
