### ISSUE TITLE
can't login if account has no calendars

### ISSUE THREAD

**Issue by y-x41** [etesync/ios#17]
app gets stuck on the "Login" screen with the circle turning (the one that appears after "Loading please wait...")

**Comment by tasn** [comment]
I just tried this with an associate account with no calendars and it seems to be fixed. Are you still getting it?

**Comment by y-x41** [comment]
Yes, I'm wrong, sorry.
Logging in works, it syncs fine, apparently. But then when you hit the refresh button it gives the above error message.

**Comment by tasn** [comment]
Not here, it doesn't. :|
What error message btw, you said it's just stuck loading.

**Comment by y-x41** [comment]
I'm even more sorry. I didn't read my original issue description before replying, only the title and your reply and assumed you it's about #20 instead.

You're right, this seems to be fixed.
