### ISSUE TITLE
Fake DAV Read Only Calendars Writeable

### ISSUE THREAD

**Issue by trymeouteh** [etesync/ios#18]
I setup EteSync on my friends iPhone and I used the fake DAV setup so they can still use iCloud. I shared two calendars with their associate account. One calendar is read and write and the other is read only. I was able to create an event on the read only calendar.

I think the fake dav calendars allow the user to read and write but not the etesync calendars unless it shared to allow read and write. I think the fake dav calendars do not sync weather the etesync calendars are read only or not.

**Comment by tasn** [comment]
Doesn't the sync itself fail with an error at least?
It's a known issue unfortunately, because Apple doesn't let you control the read-only status of calendars you create from code. :|

**Comment by trymeouteh** [comment]
I had them change the event to the correct calendar but I can do a test with a dummy event and see if this will get synced to my android.

I was not aware apple did not allow read only calendars.

**Comment by tasn** [comment]
Apple allow read-only calendars, they just don't allow you creating them from code, or at least I wasn't able to find out how to do it (if memory serves, it's been a while since I looked into it).

I can tell you for a fact that the event won't sync, as the server will block it, but the iOS app should at least error about it.

**Comment by trymeouteh** [comment]
Yes the event did not sync and etesync gave me an error on "permission denied" it also prevent any further syncing and essentially to solve this issue the owner of the calendar had to remove the associate from the calendar sync, and read them to the calendar again.

**Comment by tasn** [comment]
We are aware of the issue you described and plan on just ignoring the changes and notifying users about reverting them back.
