### ISSUE TITLE
App crashes when syncing contacts if there is no contact journal

### ISSUE THREAD

**Issue by bleetsheep** [etesync/ios#20]
Pretty much as the title says: no contact journal / address book (not sure what the right word is) was created yet and when I tried to sync my contacts, I got a stack trace. Unfortunately I didn't have the presence of mind to copy the debug info, but I'm reasonably sure this was the cause as it worked after the main account created and shared an address book with my affiliate account.

**Comment by tasn** [comment]
I'll take, a look soon. Thanks for reporting!

**Comment by y-x41** [comment]
could this be related to #17 ?

**Comment by tasn** [comment]
I'm sorry it took me a bit of time. I just tested it in an account with no address book (or calendars for that matter) and things just work fine. Are you still getting it?

**Comment by bleetsheep** [comment]
Ah, then it must be something else that made the app crash that time. As I said, I stupidly didn't copy the debug logs. It is no longer crashing exactly: syncs stay at "starting sync" for a very long time (at least some minutes while seemingly doing nothing, and if I forget to keep the screen on, it will happily wait for many hours until I turn the screen on again) but eventually works, and when starting the app I have a blank white screen for a minute or so (but eventually works too). But no, no crashes. Sorry for the misleading info!

**Comment by tasn** [comment]
Interesting info, could you please open another ticket about this other thing (it sounds like the same/similar thing).
