### ISSUE TITLE
Deleting events on iOS

### ISSUE THREAD

**Issue by Kemwer** [etesync/ios#44]
I'm getting an error after I delete an event from the calendar on iOS and then sync the EteSync iOS app. 

![IMG_1039](https://user-images.githubusercontent.com/22405971/97528247-41c47d00-197b-11eb-9ade-caa34323bee4.PNG)

When I delete an event on the Mac I have no problem with syncing afterwards and it updates all my calendars

**Comment by tasn** [comment]
Hey,

That's odd! Could you please contact me on the community chat: https://wwww.etesync.com/community-chat/ (I'm TAsn)? I'd like to investigate further but I wouldn't want you to share the answers (such as your username) publicly.
