### ISSUE TITLE
Is etesync ios abandonned ?

### ISSUE THREAD

**Issue by BirdInFire** [etesync/ios#64]
I have not really used ete sync since some time, and when i was about to go in i have seen that the website blog is deserted (not many update) the git not move and ios app isn't updated for a year, is this project (and or ios app abandonned ?)

**Comment by tasn** [comment]
No. Just very busy so don't have time to hack on the iOS app. Other repos have been getting some updates.

**Comment by tasn** [comment]
Closing btw as question was answered.
