### ISSUE TITLE
Unable to Create Account

### ISSUE THREAD

**Issue by QuezXLV** [etesync/ios#65]
I tried to sign up for an account on a desktop computer using Firefox on Ubuntu. I got to a screen that said “Deriving encryption data” and it would hang there. I tried to refresh and that brought me to the login page. I tried to log in with my credentials, and it says user not found. I tried to log in with my email address, but no email was sent to me.

**Comment by tasn** [comment]
Duplicate of https://github.com/etesync/etesync-web/issues/236
