### ISSUE TITLE
iOS doesn't delete local contacts once app is deleted

### ISSUE THREAD

**Issue by plsnotracking** [etesync/ios#75]
Scenario
1. Install etesync.
2. Sync your contacts in local after disabling iCloud sync.
3. Delete the app.
4. Install the app again, repeat 1/2. Contact will create a different collection each time you do this.

This leaves existing contacts there itself without having to delete/edit the old collection.

Current workaround, once you delete the app, switch on the sync feature, let it sync to iCloud, then go to iCloud.com, delete all contacts.

**Comment by renestalder** [comment]
Additionally annoying that iOS doesn't have a way to bulk delete contacts. The described workaround of you is the only way to remove all the contacts: Deactivate/Activate some other contacts account.

**Comment by tasn** [comment]
iOS is just very very limited as a platform with buggy contact handling APIs. We have no way of deleting the contacts when the app is deleted unfortunately.

**Comment by plsnotracking** [comment]
Platform problems.
