### ISSUE TITLE
Warning removal from apple

### ISSUE THREAD

**Issue by BirdInFire** [etesync/ios#87]
warning outated app, this time from apple : https://www.theverge.com/2022/4/29/23049576/apple-outdated-apps-removal-extension-90-days

Time to update, last time i warn you about outated app.

`As part of the App Store Improvements process, developers of apps that have not been updated within the last three years and fail to meet a minimal download threshold — meaning the app has not been downloaded at all or extremely few times during a rolling 12 month period — receive an email notifying them that their app has been identified for possible removal from the App Store.`

**Comment by tasn** [comment]
We didn't get an email, did you have an indication that we will be marked for removal?
