### ISSUE TITLE
More accurate explonation of Expo setup in readme

### ISSUE THREAD

**Issue by PatrickMis** [etesync/ios#9]
"Add CalDAV and CarDAV accounts to your iPhone as explained in this video. The account description must be exactly etesync otherwise sync won't work."

1. Typo: probably CardDAV not CarDAV.
2. There is probable group of visually impaired people (I am one of them) which cannot see the video. So please add step-by-step instructions how to add these accounts with e.g. example data or just describe steps shown on this video.
Me (and possibly other people) would be greatful.

**Comment by tasn** [comment]
Nice catch, fixed both!

**Comment by PatrickMis** [comment]
Thank you for quick response!
